[tool.poetry]
name = "mecha"
version = "0.7.2"
description = "A powerful Minecraft command library"
authors = ["Valentin Berlier <berlier.v@gmail.com>"]
license = "MIT"

homepage = "https://github.com/mcbeet/mecha"
repository = "https://github.com/mcbeet/mecha"
documentation = "https://github.com/mcbeet/mecha"

readme = "README.md"

keywords = [
  "beet",
  "minecraft",
  "datapack",
  "minecraft-commands",
  "mcfunction"
]

include = ["mecha/py.typed"]

[tool.poetry.dependencies]
python = "^3.8"
beet = ">=0.44.5"
tokenstream = "^1.2.3"

[tool.poetry.dev-dependencies]
black = "^21.10b0"
rope = "^0.21.0"
pytest = "^6.2.5"
isort = "^5.10.0"
python-semantic-release = "^7.19.2"
pytest-insta = "^0.1.10"

[tool.black]
target-version = ["py38"]
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | node_modules
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"

[tool.semantic_release]
branch = "main"
version_variable = ["mecha/__init__.py:__version__"]
version_toml = "pyproject.toml:tool.poetry.version"
major_on_zero = false
build_command = "poetry build"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
